import Head from "next/head";
import APIClient from "~/lib/services/api-client";
import type { Module } from "~/lib/types";

const apiClient = new APIClient("/catalog");

export async function getStaticProps() {
  const modules = await apiClient.getAll();

  return {
    props: {
      modules,
    },
  };
}

interface Props {
  modules: Module[];
}

export default function Home({ modules }: Props) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {modules.map((module) => (
          <div key={module.uid}>
            <h2>{module.title}</h2>
            <p>{module.summary}</p>
          </div>
        ))}
      </main>
    </>
  );
}
