import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useInView } from "react-intersection-observer";
import {
  Card,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Button } from "~/components/ui/button";

import useAllModules from "~/lib/hooks/useAllModules";
import APIClient from "~/lib/services/api-client";
import type { Module } from "~/lib/types";

const apiClient = new APIClient("/catalog");

export async function getStaticProps() {
  try {
    const initialModules = (await apiClient.getAll()).slice(0, 70);
    // Added a hard limit to the amount of data displayed on static generation to 70, as the API returns 1000+ modules
    // This is to prevent the initial load from being too slow

    return {
      props: {
        initialModules,
      },
      revalidate: 60 * 60 * 12, // 12 hours
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        initialModules: [],
      },
    };
  }
}

interface Props {
  initialModules: Module[];
}

export default function Home({ initialModules }: Props) {
  const { ref, inView } = useInView({
    rootMargin: "200px",
    threshold: 0,
  });

  const { allModules, error } = useAllModules(initialModules, inView);

  const modulesToRender = allModules || initialModules;

  if (error) {
    console.error(error);
    return (
      <div className="flex min-h-screen flex-col items-center justify-center text-white">
        <h1 className="text-2xl font-bold sm:text-4xl">Error</h1>
        <p className="text-xl">There was an error getting new data</p>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="mt-12 text-center text-6xl font-bold tracking-tight text-white">
          Microsoft Learn
        </h1>
        <div className="mt-12 flex w-full max-w-full flex-wrap justify-center gap-5">
          {modulesToRender.map((module) => (
            <Card
              key={module.uid}
              className="flex w-[350px] flex-col items-center justify-between text-center"
            >
              <CardHeader className="flex w-full items-center justify-center gap-3">
                <Image
                  src={module.icon_url}
                  width={60}
                  height={60}
                  alt={module.title + " icon"}
                />
                <CardTitle>{module.title}</CardTitle>
                <CardDescription className="line-clamp-3">
                  {module.summary}
                </CardDescription>
              </CardHeader>
              <CardFooter className="flex justify-between">
                <Button className="px-8">
                  <Link href={"/module/" + module.uid}>View</Link>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
        <p ref={ref} className="w-full p-12 text-center">
          Loading...
        </p>
      </main>
    </>
  );
}
